NeosRulez:
  DynamicResources:
    site:
      resources:
        head:
          styles:
            animateCss: 'resource://NeosRulez.Bootstrap/Private/Styles/animate.css'
            neosrulezBootstrapCss: 'resource://NeosRulez.Bootstrap/Private/Styles/styles.scss'
        footer:
          scripts:
            fsLightboxJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/fslightbox.js'
            neosrulezBootstrapJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/bootstrap.js'
            jQuery: 'resource://NeosRulez.Bootstrap/Private/JavaScript/jquery-3.6.0.js'
            waypointsJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/waypoints.js'
            parallaxJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/parallax.js'
            neosrulezBootstrapAdditionalJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/scripts.js'
